# Generated by Django 4.2.27 on 2025-12-11 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профіль", "verbose_name_plural": "Профілі"},
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="thread",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="threads",
                to="forum.category",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="forum_categ_slug_afb53f_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["created_at"], name="forum_post_created_d558d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(
                fields=["post", "user"], name="forum_postl_post_id_fcc768_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["-updated_at"], name="forum_threa_updated_3fd102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(fields=["slug"], name="forum_threa_slug_d72985_idx"),
        ),
    ]
